### ISSUE TITLE
Performance Test?

### ISSUE THREAD

**Issue by delacernamarimar** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#1]
Hello bro how's the performance wanting to buy this for macOS for mobile development and windows10 for gaming

**Comment by SaeedHaidar** [comment]
For gaming in Windows is perfect but fan is noise so you have to consider that when you buy this laptop and for Mac OS mobile app development it is okay but when I run The simulator it is kind of lagging on newer devices, I am not an app developer and I do not know if that will make a problem for you

**Comment by delacernamarimar** [comment]
Already install catalina in my end, having IOS simulator and android studio emulator with 32gb ram, it's so great to use no lag heat doesn't rises, so far this cpu is great and it's so budget friendly for casual gaming like dota,

**Comment by ghost** [comment]
I have 8 Gb ram and Android studio works well no lag in the emulator . I will be upgrading to 16 GB . But so far no emulator lag in android studio from my side
