### ISSUE TITLE
<!-- -->

### ISSUE THREAD

**Issue by ghost** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#11]

**Comment by Noor4** [comment]
I figured out the HDMI Port is hardwired to the Nvidia GPU and hence cannot use the HDMI port, so I solved this hardware issue by buying a usb to HDMI displaylink adapter . It works great. 

If anyone can help me with USB wifi dongle that would be great . The dongle I use is TP-Link TL-WN823N  and the driver is from here https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases. 

It worked well in my other clover EFI build . But using your clover EFI I seem to have the issue that the adapter isn't detected at all ? While all other USB devices like mouse, keyboard and headphones work flawlessly. Please guide me with this
