### ISSUE TITLE
smBios Problem

### ISSUE THREAD

**Issue by DaeM0nS** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#12]
Hello!

First, I’m using an Acer Nitro 5 AN515-51-50CD so that’s why it probably doesn’t works correctly.

I’ve used your EFI as référence and I’ve add done kexts / little modifications.

I’ve encountered a problem with the smBios. 
On clover, everything works Perfectly Except the TrackPad and if I disable it from my keyboard shortcut, there is no problem in the usage of the computer with an external usb mouse, but if I dont disable it and touch the trackpad, the keyboard is frozen. I’ve tried the openCore bootloader and the trackpad is working but the smBios is « empty » so iMessages / FT doesn’t works. If I’m filling the Config with the same infos / new generated infos, the trackpad doesn’t works and iMessage/FT doesn’t works too.

That’s why I’m thinking the problem is the smBios and if it isn’t empty, the trackpad doesn’t work.

I’ve tried to update OpenCore at the latest version and modify the Config.plist using OpenCore configurator app. I didn’t try to update clover atm.

Thanks if you’re able to help me or suggesting me some things / ideas.

**Comment by lrprawira** [comment]
[OpenCore Configurator is not supported in the first place](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#starting-point) *Read the "***DO NOT USE CONFIGURATORS****" point*.  
If you have followed the OpenCore guide thoroughly, your keyboard should not interfere in any way with your touchpad as your keyboard should require VoodooPS2Keyboard kext, whereas your touchpad requires VoodooI2C ELAN or HID kext with correctly configured SSDTs. You should also recheck your SMBIOS config on config.plist.  

I suggest you to follow [dortania's updated guide](https://dortania.github.io/OpenCore-Install-Guide/) and make sure you are on the correct section.
