### ISSUE TITLE
Tutorial - How to install these drivers after install Catalina?

### ISSUE THREAD

**Issue by alvarolordelo** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#14]
Thanks for the great job done here, I'm in need of some help.
Newbie here, so I've been able to make it to USB then To HD... though I'm not sure how to make it work after that step.
Would you mind making a video on youtube or any other source?
Regards,

**Comment by SaeedHaidar** [comment]
https://dortania.github.io/OpenCore-Install-Guide/
