### ISSUE TITLE
Need some help!

### ISSUE THREAD

**Issue by sokryptk** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#16]
Sorry to reach you through like this, but i'm trying to do hackintosh for my Predator Triton 300 (PT315-51). All of "what I need to work" have been fixed. Except the trackpad. So please can you tell me how you fixed your trackpad?

Thanks!

**Comment by lrprawira** [comment]
You should read through the closed issues. I commented on one of the issues regarding the touchpad issue  #10.

**Comment by sokryptk** [comment]
> You should read through the closed issues. I commented on one of the issues regarding the touchpad issue #10.

Thanks for the answer! I've gotten my trackpad working fine with some digging through in here, thanks again!

Just GPI0 was fine in my case, no XOSI was needed.
