### ISSUE TITLE
Post Install problems

### ISSUE THREAD

**Issue by LuizRafael79** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#18]
I not exactly a newbie, but i have a few problems, that i don't fix alone

Post Install, i got a black screen, cannot see anything... i searched in google and got a fix, but this sometimes work, sometimes not (Inject Intel) my video is a UHD 630, CPU i5 9300h, model 2020

Please send me in right direction... i tired from 2 days of a lot work... the install is bugged and filevault dont gone, etc... sometimes i have video, sometimes not, sometimes the vram is 7mb, sometimes is correct value (3875mb) trackpad and keyboard from nitro 5 not work, etc

**Comment by sostenesg7** [comment]
Luiz, i did an update on this EFI, to latest Opencore 0.7.4. Is fully operational and i don't have any problem:
https://github.com/sostenesg7/Nitro5-an517-51-55NT-hackintosh-EFI

**Comment by marcussacana** [comment]
> Luiz, i did an update on this EFI, to latest Opencore 0.7.4. Is fully operational and i don't have any problem: https://github.com/sostenesg7/Nitro5-an517-51-55NT-hackintosh-EFI

Hi, thx for the kit, but my notebook don't worked with your bootloader settings, the installer don't crashed or freeze... but I got a infinite boot loading... any hint?

**Comment by sostenesg7** [comment]
> > Luiz, i did an update on this EFI, to latest Opencore 0.7.4. Is fully operational and i don't have any problem: https://github.com/sostenesg7/Nitro5-an517-51-55NT-hackintosh-EFI
> 
> Hi, thx for the kit, but my notebook don't worked with your bootloader settings, the installer don't crashed or freeze... but I got a infinite boot loading... any hint?
Opa, Marcus. Qual o modelo exato do teu notebook? O meu é o AN517-51-55NT, Core i5 9300H, 8GB, TGX 1650?
Tu usou a EFI do BigSur ou do Monterey?
Se usou a do monterey, ela fica travada, por conta da kext de wifi. Recomendo usar a do BigSur.

**Comment by sostenesg7** [comment]
> > Luiz, i did an update on this EFI, to latest Opencore 0.7.4. Is fully operational and i don't have any problem: https://github.com/sostenesg7/Nitro5-an517-51-55NT-hackintosh-EFI
> 
> Hi, thx for the kit, but my notebook don't worked with your bootloader settings, the installer don't crashed or freeze... but I got a infinite boot loading... any hint?

Opa, Marcus. Qual o modelo exato do teu notebook? O meu é o AN517-51-55NT, Core i5 9300H, 8GB, GTX 1650.
Tu usou a EFI do BigSur ou do Monterey?
Se usou a do monterey, ela fica travada, por conta da kext de wifi. Recomendo usar a do BigSur.

Qualquer coisa, chama no discord: sostenesg7#0364

**Comment by marcussacana** [comment]
enviei convite de amizade
