### ISSUE TITLE
acer_AN515-54-53ED variant

### ISSUE THREAD

**Issue by delacernamarimar** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#2]
got some error, when using your efi 
![93876927_598691927389503_2132374056131887104_n](https://user-images.githubusercontent.com/16896411/79552877-3b04a580-80ce-11ea-9e61-69ec3146f342.jpg)

**Comment by SaeedHaidar** [comment]
Your laptop is not An517-51 that means do not use my config

**Comment by delacernamarimar** [comment]
got it, I use another config, but great laptop so far! thanks

**Comment by iShriyansh** [comment]
Bro can you tell me which image should i use fro this ...
