### ISSUE TITLE
TPAD issues

### ISSUE THREAD

**Issue by mesh17** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#4]
Hey is your trackpad working properly ? after sleep/restart . Pretty sure its ELAN0504 in yours too !!

**Comment by SaeedHaidar** [comment]
yeah it works perfectly

**Comment by mesh17** [comment]
> yeah it works perfectly

Also did you manage to get your bios unlocked ? There's a Forum in Win-raid.com by me with the Nitro 7 if you are interested .

**Comment by SaeedHaidar** [comment]
https://github.com/SaeedHaidar/Acer-Nitro-5-AN517-51-Bios-Unlocking

**Comment by SaeedHaidar** [comment]
it still WIP i have unlocked bios
