### ISSUE TITLE
TouchPad Right Click

### ISSUE THREAD

**Issue by jigarpatel7600** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#5]
TouchPad + all gestures Finally after month of researching

-->  Touchpad working but left click only works and right click not working

**Comment by jigarpatel7600** [comment]
Wi-Fi working with external TP-Link TL-WN722N 150Mbps Wireless USB Adapter.

**Comment by SaeedHaidar** [comment]
I know I have not found a way to Fix this yet

**Comment by SaeedHaidar** [comment]
For now you can use two finger tap as right click I will update the GitHub repository when I find a way to fix it

**Comment by SaeedHaidar** [comment]
for now i will close this issue

**Comment by SaeedHaidar** [comment]
To get right click to work go to touchpad settings in (Secondary click) choose (click in bottom right corner)

**Comment by jigarpatel7600** [comment]
Thanks. It's working 
Put 2 finger in touchpad and click left 
right click menu is visible.

**Comment by jigarpatel7600** [comment]
![Screenshot 2020-06-18 at 9 17 14 PM](https://user-images.githubusercontent.com/16982961/85044130-d982b500-b1aa-11ea-940d-2144d5c4d615.png)

Touchpad working fine in Mac os 10.15.3
after upgrade 10.15.5 not working any solution?
can you guide the kext name for modify.

**Comment by SaeedHaidar** [comment]
i have update it to the leatest version it works fine see maybe you are missing something
