### ISSUE TITLE
Issue booting into installer using OC

### ISSUE THREAD

**Issue by JustRadical** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#6]
Hey, I have a pretty similar pc to yours apart from my CPU (i5-9300H) and dGPU (GTX1650).
This is my first time setting up a hackintosh so I'm wondering if I have to change something in the config because of my CPU and/or dGPU, because everytime i try to boot into the installer it shows the boot screen then after 2-3 seconds it reboots the computer.
You made this EFI so i thought i should ask if you knew anything about why this happens..

**Comment by SaeedHaidar** [comment]
Your laptop ACPI is different then my laptop so I suggest you to begin from A to Z do not use my EFI use it just as a reference

**Comment by justradical** [comment]
Okay thank you!! 
I found some things i can use from your config.plist but im gonna check everything and change the stuff thats different

**Comment by SaeedHaidar** [comment]
for now i will cose this issue
